### ISSUE TITLE
Will listening on ipv6 be supported?

### ISSUE THREAD

**Issue by chunfengyao** [sjinks/tiny-ssh-honeypot#253]
when docker container started with this CMD.
```
--address '::'
```
log show me this error.
```
ERROR: failed to bind() to :::22: Address family not supported by protocol
```

**Comment by sjinks** [comment]
Please try the updated version :-)

**Comment by chunfengyao** [comment]
[ Error: Address already in use](https://stackoverflow.com/a/51913093/12990751)

It seems that adding a `IPV6_V6ONLY` flag on the socket will be better.

After the patch was addressed, all incoming IPV4 connections appeared as follows:
```
fakessh  | 2024-04-10 12:41:13 tiny-ssh-honeypot: [::ffff:182.92.165.47:50852 => ::ffff:192.168.1.1:22]: incoming connection
fakessh  | 2024-04-10 12:41:22 tiny-ssh-honeypot: [::ffff:182.92.165.47:50852 => ::ffff:192.168.1.1:22]: SSH error: IO error
fakessh  | 2024-04-10 12:41:22 tiny-ssh-honeypot: [::ffff:182.92.165.47:50852 => ::ffff:192.168.1.1:22]: closing connection
```

**Comment by chunfengyao** [comment]
> [ Error: Address already in use](https://stackoverflow.com/a/51913093/12990751)
> 
> It seems that adding a `IPV6_V6ONLY` flag on the socket will be better.
> 
> After the patch was addressed, all incoming IPV4 connections appeared as follows:
> 
> ```
> fakessh  | 2024-04-10 12:41:13 tiny-ssh-honeypot: [::ffff:182.92.165.47:50852 => ::ffff:192.168.1.1:22]: incoming connection
> fakessh  | 2024-04-10 12:41:22 tiny-ssh-honeypot: [::ffff:182.92.165.47:50852 => ::ffff:192.168.1.1:22]: SSH error: IO error
> fakessh  | 2024-04-10 12:41:22 tiny-ssh-honeypot: [::ffff:182.92.165.47:50852 => ::ffff:192.168.1.1:22]: closing connection
> ```

docker-compose.yml
```
...
command: ["-b","::","-b","0.0.0.0","-p","22"]
...
```

**Comment by sjinks** [comment]
> Failed to bind() to 0.0.0.0:22: Address in use

Yes, because `::` means "all interfaces"; this also includes `0.0.0.0`.

**Comment by sjinks** [comment]
```
$ ./tiny-ssh-honeypot --address :: --port 2222
2024-04-10 16:06:56 tiny-ssh-honeypot: [::ffff:127.0.0.1:45822 => ::ffff:127.0.0.1:2222]: incoming connection
2024-04-10 16:07:03 tiny-ssh-honeypot: [::ffff:127.0.0.1:45822 => ::ffff:127.0.0.1:2222]: login attempt for user: root (password: q)
2024-04-10 16:07:04 tiny-ssh-honeypot: [::ffff:127.0.0.1:45822 => ::ffff:127.0.0.1:2222]: SSH error: IO error
2024-04-10 16:07:04 tiny-ssh-honeypot: [::ffff:127.0.0.1:45822 => ::ffff:127.0.0.1:2222]: closing connection
```

**Comment by sjinks** [comment]
I just pushed the new version (#255); it sets the `IPV6_V6ONLY` flag. Please take a look.
